name: Push Aution

on:
  push:
  workflow_dispatch:

jobs:
  nginx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags: [mainline]
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set current date as env variable
        run: echo "BuildTime=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Make nginx-builder for tag ${{ matrix.tags }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./nginx/${{ matrix.tags }}/Dockerfile.builder
          push: false
          tags: |
            nginx:builder

      - name: Make nginx-modules for tag ${{ matrix.tags }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./nginx/${{ matrix.tags }}/Dockerfile.modules
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:modules-${{ env.BuildTime }}

      - name: Make nginx-full for tag ${{ matrix.tags }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./nginx/${{ matrix.tags }}/Dockerfile.full
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:full-${{ env.BuildTime }}

      - name: Make nginx for tag ${{ matrix.tags }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./nginx/${{ matrix.tags }}/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:${{ env.BuildTime }}

      - name: Make nginx-modules for tag ${{ matrix.tags }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./nginx/${{ matrix.tags }}/Dockerfile.fixed
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx:fixed-${{ env.BuildTime }}